config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root to: 'session#new'
  post 'login' => 'session#login'

  get 'groups' => 'groups#new'
  post 'groups' => 'groups#create'

  get 'users' => 'users#new'
  patch 'users' => 'users#create'

  get 'role' => 'role#new'
  post 'role' => 'role#create'

  get 'games' => 'games#main'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charactor_list.rb
class CharactorList
  def self.all
    @all ||= {
      merlin: Merlin.instance,
      percival: Percival.instance,
      arthur_subordinates: ArthurSubordinates.instance,
      assassin: Assassin.instance,
      mordred: Mordred.instance,
      morgana: Morgana.instance,
      oberon: Oberon.instance,
      mordred_subordinates: MordredSubordinates.instance
    }
  end

  def self.justice
    @justice ||= {
      merlin: Merlin.instance,
      percival: Percival.instance,
      arthur_subordinates1: ArthurSubordinates.instance,
      arthur_subordinates2: ArthurSubordinates.instance,
      arthur_subordinates3: ArthurSubordinates.instance,
      arthur_subordinates4: ArthurSubordinates.instance,
      arthur_subordinates5: ArthurSubordinates.instance
    }
  end

  def self.evil
    @evil ||= {
      assassin: Assassin.instance,
      mordred: Mordred.instance,
      morgana: Morgana.instance,
      oberon: Oberon.instance,
      mordred_subordinates1: MordredSubordinates.instance,
      mordred_subordinates2: MordredSubordinates.instance,
      mordred_subordinates3: MordredSubordinates.instance
    }
  end
end

app/models/charactors/arthur_subordinates.rb
class ArthurSubordinates < CharactorBase
  def initialize
    super
    @id = 'arthur_subordinates'
    @name = ARTHUR_SUBORDINATES
  end
end

app/models/charactors/assassin.rb
class Assassin < CharactorBase
  def initialize
    super
    @id = 'assassin'
    @name = ASSASSIN
    @role_name[:merlin] = MORDRED_SUBORDINATES
    @role_name[:mordred] = MORDRED_SUBORDINATES
    @role_name[:morgana] = MORDRED_SUBORDINATES
    @role_name[:mordred_subordinates] = MORDRED_SUBORDINATES
  end
end

app/models/charactors/charactor_base.rb
class CharactorBase
  MERLIN = 'マーリン'.freeze
  PERCIVAL = 'パーシヴァル'.freeze
  ARTHUR_SUBORDINATES = 'アーサー王の忠実な部下'.freeze
  ASSASSIN = '暗殺者'.freeze
  MORDRED = 'モードレッド'.freeze
  MORGANA = 'モルガナ'.freeze
  OBERON = 'オベロン'.freeze
  MORDRED_SUBORDINATES = 'モードレッドの手下'.freeze

  attr_reader :id, :name

  def initialize
    @id = ''
    @name = ''
    @role_name = {
      merlin: '',
      percival: '',
      arthur_subordinates: '',
      assassin: '',
      mordred: '',
      morgana: '',
      oberon: '',
      mordred_subordinates: ''
    }
  end

  def display_name(role_id)
    @role_name[role_id.to_sym]
  end

  public_class_method

  def self.instance
    @instance ||= new
  end
end

app/models/charactors/merlin.rb
class Merlin < CharactorBase
  def initialize
    super
    @id = 'merlin'
    @name = MERLIN
    @role_name[:percival] = MERLIN
  end
end

app/models/charactors/mordred.rb
class Mordred < CharactorBase
  def initialize
    super
    @id = 'mordred'
    @name = MORDRED
    @role_name[:assassin] = MORDRED_SUBORDINATES
    @role_name[:morgana] = MORDRED_SUBORDINATES
    @role_name[:mordred_subordinates] = MORDRED_SUBORDINATES
  end
end

app/models/charactors/mordred_subordinates.rb
class MordredSubordinates < CharactorBase
  def initialize
    super
    @id = 'mordred_subordinates'
    @name = MORDRED_SUBORDINATES
    @role_name[:merlin] = MORDRED_SUBORDINATES
    @role_name[:assassin] = MORDRED_SUBORDINATES
    @role_name[:mordred] = MORDRED_SUBORDINATES
    @role_name[:morgana] = MORDRED_SUBORDINATES
    @role_name[:mordred_subordinates] = MORDRED_SUBORDINATES
  end
end

app/models/charactors/morgana.rb
class Morgana < CharactorBase
  def initialize
    super
    @id = 'morgana'
    @name = MORGANA
    @role_name[:merlin] = MORDRED_SUBORDINATES
    @role_name[:percival] = MERLIN
    @role_name[:assassin] = MORDRED_SUBORDINATES
    @role_name[:mordred] = MORDRED_SUBORDINATES
    @role_name[:mordred_subordinates] = MORDRED_SUBORDINATES
  end
end

app/models/charactors/oberon.rb
class Oberon < CharactorBase
  def initialize
    super
    @id = 'oberon'
    @name = OBERON
    @role_name[:merlin] = MORDRED_SUBORDINATES
  end
end

app/models/charactors/percival.rb
class Percival < CharactorBase
  def initialize
    super
    @id = 'percival'
    @name = PERCIVAL
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, dependent: :delete_all
  accepts_nested_attributes_for :users

  def distribute_role(role_ids)
    users.zip(role_ids).each do |user, role_id|
      user.update(role_id: role_id)
    end
  end

  public_class_method

  def self.find_by_name(name)
    Group.where(name: name).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :group

  def role
    @role ||= CharactorList.all[role_id.to_sym]
  end

  public_class_method

  def self.find_by_name(name)
    User.where(name: name).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_group
    @current_group ||= Group.find(session[:group_id])
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def main
    @group = current_group
    @user = current_user
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    session[:group_id] = nil
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    render 'new' && return unless @group.save
    session[:group_id] = @group.id
    redirect_to users_path
  end

  private

  def group_params
    params.require(:group).permit(:name).merge(capacity: params[:commit])
  end
end

app/controllers/role_controller.rb
class RoleController < ApplicationController
  def new
  end

  def create
    role_ids = role_params.shuffle.map { |id| id.gsub(/[0-9]/, '') }
    current_group.distribute_role(role_ids)
    redirect_to games_path
  end

  private

  def role_params
    params.require(:role)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def login
    group = Group.find_by(name: params[:group_name])
    user = User.find_by(name: params[:user_name])
    render 'new' && return unless group && user
    session[:group_id] = group.id
    session[:user_id] = user.id
    redirect_to games_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @group = current_group
    @group.users.destroy_all unless @group.users.blank?
    @group.capacity.times { @group.users.build }
  end

  def create
    users = params[:group][:users_attributes].values
    users.each do |user|
      current_group.users << User.create(name: user[:name])
    end
    session[:user_id] = current_group.users.first.id
    redirect_to role_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/main.html.slim
h1 game main page

p= @user.name
p= @user.role.name

table.table.table-border
  tbody
    tr
      th ユーザ名
      th ロール
    - @group.users.each do |user|
      - next if @user.id == user.id
      tr
        td= user.name
        td= user.role.display_name(@user.role_id)

.center
  p#ready_user_number 0/5
  button#ready.btn.btn-primary 準備完了

app/views/groups/new.html.slim
h2.page-header グループ作成

= form_for @group, url: groups_path, class: 'form-group' do |f|
  = f.label :name, 'グループ名'
  = f.text_field :name, class: 'form-control'
  br
  = f.label :capacity, '参加人数'
  .row
    - [5, 6, 7, 8, 9, 10].each do |i|
      div.col-md-2.col-xs-6 style="margin: 3px 0 3px 0"
        = f.submit i, class: 'btn btn-lg btn-primary col-xs-12'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Avalon
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .navbar.navbar-default.navbar-inverse
      .container
        .navbar-header
          a.navbar-brand href="#" Avalon
    .container
      = yield
    hr
    footer
      .container
        p.right Copyright &copy; 2016 gembaf All Rights Reserved.

app/views/role/new.html.slim
h2.page-header ロール選択

= form_tag role_path, class: 'form-group' do
  .row
    .col-xs-12.col-md-6
      h3.page-header style="color: blue" 正義陣営
      - CharactorList.justice.each do |id, charactor|
        .col-xs-12
          label
            = check_box_tag 'role[]', id
            = charactor.name
    .col-xs-12.col-md-6
      h3.page-header style="color: red" 邪悪陣営
      - CharactorList.evil.each do |id, charactor|
        .col-xs-12
          label
            = check_box_tag 'role[]', id
            = charactor.name
  .row
    br
    .center
      button.btn.btn-primary 決定

app/views/session/new.html.slim
h2.page-header ログイン

= form_tag login_path, class: 'form-group' do
  = label :group_name, 'グループ名'
  = text_field_tag :group_name, nil, class: 'form-control'
  br
  = label :user_name, 'ユーザ名'
  = text_field_tag :user_name, nil, class: 'form-control'
  br
  .center
    button.btn.btn-primary Login

app/views/users/new.html.slim
h2.page-header 参加者登録

= form_for @group, url: users_path, class: 'form-group' do |f|
  .row
    - cnt = 0
    = f.fields_for :users do |user|
      .col-xs-12.col-sm-6.col-md-4.col-lg-3
        - if cnt == 0
          = user.label :name, 'ホスト'
        - else
          = user.label :name, "ユーザ #{cnt}"
        - cnt += 1
        = user.text_field :name, class: 'form-control'
  br
  .center
    button.btn.btn-primary Start